Bump MSRV to 1.81 due to dep requirements (#327)
Without this, builds will fail 

```
error: rustc 1.80.0 is not supported by the following packages:
  derive_more@2.1.1 requires rustc 1.81.0
  derive_more-impl@2.1.1 requires rustc 1.81.0
  indexmap@2.12.1 requires rustc 1.82
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.80.0
```

example: https://github.com/mikaelmello/inquire/actions/runs/20666926694/job/59341003795?pr=326